name: pre build
description: 'steps before building R3BRoot'

runs:
  using: composite
  steps:
    - name: set env variables
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        echo "UCESB_DIR=$GITHUB_WORKSPACE/ucesb/" >> $GITHUB_ENV
        export SIMPATH=${CVMDIR}/${{ matrix.os }}/fairsoft/jan24p1
        echo "SIMPATH=${SIMPATH}" >> $GITHUB_ENV
        echo "FAIRROOTPATH=${CVMDIR}/${{ matrix.os }}/fairroot/v18.8.2_jan24p1" >> $GITHUB_ENV
        echo "${SIMPATH}/bin" >> $GITHUB_PATH
        # variables for ccache
        echo "CCACHE_BASEDIR=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
        echo "CCACHE_DIR=${GITHUB_WORKSPACE}/.ccache" >> $GITHUB_ENV
        echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
        echo "CCACHE_COMPRESSLEVEL=6" >> $GITHUB_ENV
        echo "SOURCEDIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "BUILDDIR=$GITHUB_WORKSPACE/build" >> $GITHUB_ENV
        echo "cacheSHA=$([[ ${{github.event_name}} = "push" ]] && git rev-parse --short HEAD || git rev-parse --short HEAD^)" >> $GITHUB_ENV
      shell: bash


    - name: mount cvmfs
      run: |
        apt-get update
        apt-get install --fix-missing -y sudo && sudo apt install -y lsb-release
        lsb_release -a
        wget https://cernbox.cern.ch/remote.php/dav/public-files/RmnTeeOZpYjCJQb/masterkey.gsi.de.pub
        mv masterkey.gsi.de.pub /etc/cvmfs/keys
        cp .github/config/fairsoft.gsi.de.conf /etc/cvmfs/config.d
        echo "CVMFS_USER=$(whoami)" >> /etc/cvmfs/config.d/fairsoft.gsi.de.conf
        mkdir -p ${CVMDIR}
        mount -t cvmfs fairsoft.gsi.de ${CVMDIR}
        mkdir -p ${UCESB_DIR}
        mkdir -p ${CCACHE_DIR}
      shell: bash
