# SPDX-License-Identifier: LGPL-3.0-or-later

name: Check AUTHORS and CONTRIBUTORS in metadata

on:
  push:
    paths:
    - AUTHORS
    - CONTRIBUTORS
    - codemeta.json
    - .zenodo.json
  pull_request:
    paths:
    - AUTHORS
    - CONTRIBUTORS
    - codemeta.json
    - .zenodo.json

jobs:
  metadata-check:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
      - name: Update Metadata
        run: python meta_update.py
      - name: Verify Changes
        run: git diff --exit-code || echo "Metadata files require updates. Please commit the changes."
